export const opportunities = [
  {
    id: 1,
    category: "Greening",
    title: "Urban Greening: Community Garden Creation",
    location: "New York",
    date: "September 10",
    latitude: 40.7128,
    longitude: -74.0060,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Join us in turning vacant urban spaces into vibrant community gardens. This initiative focuses on creating green spaces in city areas, promoting local food production, and enhancing community well-being."
  },
  {
    id: 2,
    category: "Clean-up",
    title: "Beach Clean-up: Save Our Shores",
    location: "Miami",
    date: "September 15",
    latitude: 25.7617,
    longitude: -80.1918,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Help us protect marine life by participating in our beach clean-up event. We will be removing litter and debris from the shores to ensure a safe and clean environment for both people and wildlife."
  },
  {
    id: 3,
    category: "Wildlife",
    title: "Wildlife Conservation: Habitat Restoration",
    location: "Yellowstone",
    date: "September 20",
    latitude: 44.4280,
    longitude: -110.5885,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Join us in restoring natural habitats for endangered species. This project focuses on rebuilding ecosystems that are essential for the survival of local wildlife."
  },
  {
    id: 4,
    category: "Greening",
    title: "Green Roof Initiative: Urban Sustainability",
    location: "San Francisco",
    date: "September 25",
    latitude: 37.7749,
    longitude: -122.4194,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Help us create green roofs in urban areas to combat the heat island effect. These roofs will not only improve air quality but also provide habitats for urban wildlife."
  },
  {
    id: 5,
    category: "Clean-up",
    title: "River Clean-up: Protecting Freshwater Ecosystems",
    location: "Chicago",
    date: "October 1",
    latitude: 41.8781,
    longitude: -87.6298,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Join us in cleaning up our local rivers to protect freshwater ecosystems. Your efforts will help ensure clean water for both people and wildlife."
  },
  {
    id: 6,
    category: "Wildlife",
    title: "Wildlife Monitoring: Tracking Endangered Species",
    location: "Everglades",
    date: "October 5",
    latitude: 25.2866,
    longitude: -80.8987,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Participate in tracking and monitoring endangered species in their natural habitats. This data is vital for the conservation efforts of these species."
  },
  {
    id: 7,
    category: "Greening",
    title: "Urban Forest: Tree Planting for Clean Air",
    location: "Denver",
    date: "October 12",
    latitude: 39.7392,
    longitude: -104.9903,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Help us plant trees in urban areas to improve air quality and provide green spaces for the community. Every tree counts in the fight against climate change."
  },
  {
    id: 8,
    category: "Clean-up",
    title: "Park Clean-up: Revitalize Your Local Park",
    location: "Boston",
    date: "October 18",
    latitude: 42.3601,
    longitude: -71.0589,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Join your community in revitalizing local parks by cleaning up litter and maintaining green spaces. Your efforts will create a cleaner, more enjoyable environment for everyone."
  },
  {
    id: 9,
    category: "Wildlife",
    title: "Pollinator Garden Creation: Support Local Bees",
    location: "Austin",
    date: "October 25",
    latitude: 30.2672,
    longitude: -97.7431,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Help us create pollinator gardens to support local bee populations. These gardens are vital for the survival of bees, which are essential for pollinating our food crops."
  },
  {
    id: 10,
    category: "Greening",
    title: "School Greening: Planting Trees at Local Schools",
    location: "Austin",
    date: "November 1",
    latitude: 47.6062,
    longitude: -122.3321,
    link: "https://google.com",
    mainImageUrl: "../image1.webp",
    galleryImages: [
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
      "../image1.webp",
    ],
    description: "Join us in planting trees at local schools to create green spaces for students. These green spaces provide shade, improve air quality, and enhance the learning environment."
  }
];
